on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  

    - name: Build
      uses: okteto/actions/build@ea231cf5223ee393276c0b9a97ac57ec6c7110a4
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        tag: ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ github.sha }}

    - name: Get Kubeconfig
      uses: okteto/actions/namespace@ea231cf5223ee393276c0b9a97ac57ec6c7110a4
      id: namespace
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: actions-rberrelleza
    
    - name: Deploy and Wait
      uses: okteto/actions/deploy@ea231cf5223ee393276c0b9a97ac57ec6c7110a4
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}  
      with:
        namespace: actions-rberrelleza
        manifest: k8s.yml
        tag: ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ github.sha }}
        waitOn: deployment/hello-world
    
    - name: Verify
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://hello-world-actions-rberrelleza.cloud.okteto.net"
        expected-statuses: "200"
        
