on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    
    - name: Build
      uses: okteto/actions/build@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        tag: registry.cloud.okteto.net/actions-rberrelleza/hello-world:${{ github.sha }}

    - name: Get Kubeconfig
      uses: okteto/actions/namespace@master
      id: namespace
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: actions-rberrelleza
    
    - name: Deploy and Wait
      uses: okteto/actions/deploy@master
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}  
      with:
        namespace: actions-rberrelleza
        manifest: k8s.yml
        tag: registry.cloud.okteto.net/actions-rberrelleza/hello-world:${{ github.sha }}
        waitOn: deployment/hello-world
    
    - name: Verify
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://hello-world-actions-rberrelleza.cloud.okteto.net"
        expected-statuses: "200"
        
