on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: okteto/actions/namespace@091c0215e593c895b64702dfaaefcbea7a774a1f
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: actions-rberrelleza

    - uses: okteto/actions/deploy@091c0215e593c895b64702dfaaefcbea7a774a1f
      with:
        namespace: actions-rberrelleza
        manifests: k8s.yml
        image: okteto/hello-world
        tag: golang
          