on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: okteto/actions/update@f52f4ed5e30d099a14ab9ef233b9bae812d320df
      with:
        manifests: k8s.yml
        image: okteto/hello-world
        tag: dev

    - uses: okteto/actions/namespace@f52f4ed5e30d099a14ab9ef233b9bae812d320df
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: actions-rberrelleza

    - uses: okteto/actions/deploy@f52f4ed5e30d099a14ab9ef233b9bae812d320df
      with:
        namespace: actions-rberrelleza
        manifests: k8s.yml
          