on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: okteto/actions/namespace@f204e23d224362a2eb3e98969e8ac4651805478a
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: actions-rberrelleza

    - uses: okteto/actions/deploy@f204e23d224362a2eb3e98969e8ac4651805478a
      with:
        namespace: actions-rberrelleza
        manifests: k8s.yml
        image: okteto/hello-world
        tag: golang
          