on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: okteto/actions/namespace@5fc7361929e77b774a953658fd52e8fb78c88674
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: actions-rberrelleza
        
    - uses: okteto/actions/deploy@5fc7361929e77b774a953658fd52e8fb78c88674
      with:
        namespace: actions-rberrelleza
        manifests: |
          k8s.yml