on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: okteto/actions/update@076d8174cdf5a4948c0e09cfacd02fc6c140b663
      with:
        manifests: k8s.yml
        image: okteto/hello-world
        tag: golang

    - uses: okteto/actions/namespace@076d8174cdf5a4948c0e09cfacd02fc6c140b663
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: actions-rberrelleza

    - uses: okteto/actions/deploy@076d8174cdf5a4948c0e09cfacd02fc6c140b663
      with:
        namespace: actions-rberrelleza
        manifests: k8s.yml
          